### ISSUE TITLE
IndexError while running script

### ISSUE THREAD

**Issue by asan-emirsaleh** [micahvista/VACmap#1]
Hello!
Thank you for introducing promising tool!
I have installed VACmap as you suggested in your README.md and and ran it on my data. But the IndexError: list index out of range was raised.
The command was
`conda run -n vacmap-env vacmap -ref ${REF} -read ${QUERY} --eqx --cs -mode L`
The error message was
```
Traceback (most recent call last):
  File "/home/asan/miniconda3/envs/vacmap-env/bin/vacmap", line 4, in <module>
    __import__('pkg_resources').run_script('VACmap==1.0', 'vacmap')
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/VACmap-1.0-py3.10-linux-x86_64.egg/EGG-INFO/scripts/vacmap", line 204, in <module>
    onemapinfolist, (alignment_list,raw_alignment_list), one_mapinfo, f_redo_ratio = mammap.get_readmap_DP_test(readid, str(Seq(testseq).reverse_complement()),  contig2start, contig2seq, index_object, index2contig, hastra = True, refine = True, debug = False, H = H)  
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/VACmap-1.0-py3.10-linux-x86_64.egg/vacmap/mammap_ccs.py", line 11134, in get_readmap_DP_test
    mapq, scores, raw_alignment_list, redo_flag = decode_hit(index_object, index2contig, testseq, testseq_len, contig2start, kmersize, contig2seq, skipcost = golbal_skipcost, maxdiff = golbal_maxdiff, maxgap = 200, check_num = check_num, c_bias = 5000, bin_size = bin_size, overlapprecentage = 0.5, hastra = hastra, H = H, mid_occ = mid_occ)
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/VACmap-1.0-py3.10-linux-x86_64.egg/vacmap/mammap_ccs.py", line 10834, in decode_hit
    f_redo_ratio = min(abs(testseq_len/(primary_scores_List[0][0]+1e-7)), 20)
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/numba/typed/typedlist.py", line 370, in __getitem__
    return _getitem(self, i)
  File "/home/asan/miniconda3/envs/vacmap-env/lib/python3.10/site-packages/numba/typed/listobject.py", line 662, in handle_index
    raise IndexError("list index out of range")
IndexError: list index out of range

ERROR conda.cli.main_run:execute(124): `conda run vacmap -ref <ref.fasta> -read <query.fasta> -mode L --eqx --cs` failed. (See above for error)
```

**Comment by micahvista** [comment]
Dear Asan:

Thank you for reporting this issue. I have updated the code accordingly. Could you please reinstall the latest version and see if the problem persists?

Best regards,
Hongyu Ding

**Comment by micahvista** [comment]
Dear Asan:
Using following command to reinstall

rm -r VACmap
git clone https://github.com/micahvista/VACmap.git
cd VACmap
conda activate vacmap_env
python setup.py install

Best regards,
Hongyu Ding
