### ISSUE TITLE
No module named 'edlib'

### ISSUE THREAD

**Issue by dukecomeback** [micahvista/VACmap#4]
/miniconda3/envs/busco/bin/vacmap:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('VACmap==1.0', 'vacmap')
Traceback (most recent call last):
  File "/home/k_d239/miniconda3/envs/busco/bin/vacmap", line 4, in <module>
    __import__('pkg_resources').run_script('VACmap==1.0', 'vacmap')
  File "/home/k_d239/miniconda3/envs/busco/lib/python3.9/site-packages/pkg_resources/__init__.py", line 680, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/k_d239/miniconda3/envs/busco/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1516, in run_script
    exec(code, namespace, namespace)
  File "/mmfs1/home/k_d239/miniconda3/envs/busco/lib/python3.9/site-packages/VACmap-1.0-py3.9-linux-x86_64.egg/EGG-INFO/scripts/vacmap", line 9, in <module>
    import edlib
ModuleNotFoundError: No module named 'edlib'

Hi, I got the above error after the installation. Is there a simple way to fix this? Thank you.

**Comment by micahvista** [comment]
Hi, 

I apologize for the inconvenience. It seems there might have been an error due to an unsuccessful installation. Could you please try reinstalling VACmap as recommended? 
Alternatively, you can run the command pip install edlib. 

Best regards, 
Hongyu Ding
